# Generated by Django 3.0.6 on 2020-05-10 15:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('asmdapp', '0005_auto_20200510_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningmodel',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
